// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/clients/interfaces/companyClient.go

// Package client_mocks is a generated GoMock package.
package client_mocks

import (
	company_grpc "github.com/go-park-mail-ru/2019_2_Comandus/internal/app/company/delivery/grpc/company_grpc"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCompanyClient is a mock of CompanyClient interface
type MockCompanyClient struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyClientMockRecorder
}

// MockCompanyClientMockRecorder is the mock recorder for MockCompanyClient
type MockCompanyClientMockRecorder struct {
	mock *MockCompanyClient
}

// NewMockCompanyClient creates a new mock instance
func NewMockCompanyClient(ctrl *gomock.Controller) *MockCompanyClient {
	mock := &MockCompanyClient{ctrl: ctrl}
	mock.recorder = &MockCompanyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCompanyClient) EXPECT() *MockCompanyClientMockRecorder {
	return m.recorder
}

// CreateCompanyOnServer mocks base method
func (m *MockCompanyClient) CreateCompanyOnServer(arg0 int64) (*company_grpc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompanyOnServer", arg0)
	ret0, _ := ret[0].(*company_grpc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompanyOnServer indicates an expected call of CreateCompanyOnServer
func (mr *MockCompanyClientMockRecorder) CreateCompanyOnServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompanyOnServer", reflect.TypeOf((*MockCompanyClient)(nil).CreateCompanyOnServer), arg0)
}

// GetCompanyFromServer mocks base method
func (m *MockCompanyClient) GetCompanyFromServer(arg0 int64) (*company_grpc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyFromServer", arg0)
	ret0, _ := ret[0].(*company_grpc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyFromServer indicates an expected call of GetCompanyFromServer
func (mr *MockCompanyClientMockRecorder) GetCompanyFromServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyFromServer", reflect.TypeOf((*MockCompanyClient)(nil).GetCompanyFromServer), arg0)
}
