// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/user/usecase.go

// Package test is a generated GoMock package.
package test

import (
	model "github.com/go-park-mail-ru/2019_2_Comandus/internal/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserUsecase is a mock of UserUcase interface
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method
func (m *MockUserUsecase) CreateUser(arg0 *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser
func (mr *MockUserUsecaseMockRecorder) CreateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserUsecase)(nil).CreateUser), arg0)
}

// VerifyUser mocks base method
func (m *MockUserUsecase) VerifyUser(arg0 *model.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUser", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUser indicates an expected call of VerifyUser
func (mr *MockUserUsecaseMockRecorder) VerifyUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUser", reflect.TypeOf((*MockUserUsecase)(nil).VerifyUser), arg0)
}

// EditUser mocks base method
func (m *MockUserUsecase) EditUser(newUser, oldUser *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUser", newUser, oldUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUser indicates an expected call of EditUser
func (mr *MockUserUsecaseMockRecorder) EditUser(newUser, oldUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUser", reflect.TypeOf((*MockUserUsecase)(nil).EditUser), newUser, oldUser)
}

// EditUserPassword mocks base method
func (m *MockUserUsecase) EditUserPassword(passwords *model.BodyPassword, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUserPassword", passwords, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUserPassword indicates an expected call of EditUserPassword
func (mr *MockUserUsecaseMockRecorder) EditUserPassword(passwords, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUserPassword", reflect.TypeOf((*MockUserUsecase)(nil).EditUserPassword), passwords, user)
}

// Find mocks base method
func (m *MockUserUsecase) Find(arg0 int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockUserUsecaseMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserUsecase)(nil).Find), arg0)
}

// SetUserType mocks base method
func (m *MockUserUsecase) SetUserType(user *model.User, userType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserType", user, userType)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserType indicates an expected call of SetUserType
func (mr *MockUserUsecaseMockRecorder) SetUserType(user, userType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserType", reflect.TypeOf((*MockUserUsecase)(nil).SetUserType), user, userType)
}

// GetRoles mocks base method
func (m *MockUserUsecase) GetRoles(user *model.User) ([]*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", user)
	ret0, _ := ret[0].([]*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles
func (mr *MockUserUsecaseMockRecorder) GetRoles(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockUserUsecase)(nil).GetRoles), user)
}

// GetAvatar mocks base method
func (m *MockUserUsecase) GetAvatar(user *model.User) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", user)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar
func (mr *MockUserUsecaseMockRecorder) GetAvatar(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockUserUsecase)(nil).GetAvatar), user)
}
