// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/user-response/repository.go

// Package mock_user_response is a generated GoMock package.
package mock_user_response

import (
	model "github.com/go-park-mail-ru/2019_2_Comandus/internal/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(response *model.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), response)
}

// Edit mocks base method
func (m *MockRepository) Edit(response *model.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit
func (mr *MockRepositoryMockRecorder) Edit(response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockRepository)(nil).Edit), response)
}

// ListForFreelancer mocks base method
func (m *MockRepository) ListForFreelancer(arg0 int64) ([]model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForFreelancer", arg0)
	ret0, _ := ret[0].([]model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForFreelancer indicates an expected call of ListForFreelancer
func (mr *MockRepositoryMockRecorder) ListForFreelancer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForFreelancer", reflect.TypeOf((*MockRepository)(nil).ListForFreelancer), arg0)
}

// ListForManager mocks base method
func (m *MockRepository) ListForManager(arg0 int64) ([]model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForManager", arg0)
	ret0, _ := ret[0].([]model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForManager indicates an expected call of ListForManager
func (mr *MockRepositoryMockRecorder) ListForManager(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForManager", reflect.TypeOf((*MockRepository)(nil).ListForManager), arg0)
}

// Find mocks base method
func (m *MockRepository) Find(arg0 int64) (*model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockRepositoryMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0)
}
