global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: ['89.208.211.100:8080']

  - job_name: 'system'
    static_configs:
      - targets: ['89.208.211.100:9100']