// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Company ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Company ) UnmarshalJSON([]byte) error { return nil }
func ( Company ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Company ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Company *Company

func ( CompanyOutput ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CompanyOutput ) UnmarshalJSON([]byte) error { return nil }
func ( CompanyOutput ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CompanyOutput ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CompanyOutput *CompanyOutput
