// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/user-contract/usecase.go

// Package mock_user_contract is a generated GoMock package.
package test

import (
	model "github.com/go-park-mail-ru/2019_2_Comandus/internal/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateContract mocks base method
func (m *MockUsecase) CreateContract(user *model.User, responseId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContract", user, responseId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContract indicates an expected call of CreateContract
func (mr *MockUsecaseMockRecorder) CreateContract(user, responseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContract", reflect.TypeOf((*MockUsecase)(nil).CreateContract), user, responseId)
}

// SetAsDone mocks base method
func (m *MockUsecase) SetAsDone(user *model.User, contractId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAsDone", user, contractId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAsDone indicates an expected call of SetAsDone
func (mr *MockUsecaseMockRecorder) SetAsDone(user, contractId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAsDone", reflect.TypeOf((*MockUsecase)(nil).SetAsDone), user, contractId)
}

// ReviewContract mocks base method
func (m *MockUsecase) ReviewContract(user *model.User, contractId int64, grade int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewContract", user, contractId, grade)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReviewContract indicates an expected call of ReviewContract
func (mr *MockUsecaseMockRecorder) ReviewContract(user, contractId, grade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewContract", reflect.TypeOf((*MockUsecase)(nil).ReviewContract), user, contractId, grade)
}
