// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/user-response/usecase.go

// Package mock_user_response is a generated GoMock package.
package mock_user_response

import (
	model "github.com/go-park-mail-ru/2019_2_Comandus/internal/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateResponse mocks base method
func (m *MockUsecase) CreateResponse(user *model.User, jobId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResponse", user, jobId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResponse indicates an expected call of CreateResponse
func (mr *MockUsecaseMockRecorder) CreateResponse(user, jobId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResponse", reflect.TypeOf((*MockUsecase)(nil).CreateResponse), user, jobId)
}

// GetResponses mocks base method
func (m *MockUsecase) GetResponses(user *model.User) (*[]model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponses", user)
	ret0, _ := ret[0].(*[]model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponses indicates an expected call of GetResponses
func (mr *MockUsecaseMockRecorder) GetResponses(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponses", reflect.TypeOf((*MockUsecase)(nil).GetResponses), user)
}

// AcceptResponse mocks base method
func (m *MockUsecase) AcceptResponse(user *model.User, responseId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptResponse", user, responseId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptResponse indicates an expected call of AcceptResponse
func (mr *MockUsecaseMockRecorder) AcceptResponse(user, responseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptResponse", reflect.TypeOf((*MockUsecase)(nil).AcceptResponse), user, responseId)
}

// DenyResponse mocks base method
func (m *MockUsecase) DenyResponse(user *model.User, responseId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyResponse", user, responseId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DenyResponse indicates an expected call of DenyResponse
func (mr *MockUsecaseMockRecorder) DenyResponse(user, responseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyResponse", reflect.TypeOf((*MockUsecase)(nil).DenyResponse), user, responseId)
}
