// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/freelancer/delivery/grpc/freelancer_grpc/freelancer.proto

package freelancer_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Freelancer struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	TagLine              string   `protobuf:"bytes,7,opt,name=TagLine,proto3" json:"TagLine,omitempty"`
	Overview             string   `protobuf:"bytes,8,opt,name=Overview,proto3" json:"Overview,omitempty"`
	ExperienceLevelId    int64    `protobuf:"varint,9,opt,name=ExperienceLevelId,proto3" json:"ExperienceLevelId,omitempty"`
	SpecialityId         int64    `protobuf:"varint,10,opt,name=SpecialityId,proto3" json:"SpecialityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Freelancer) Reset()         { *m = Freelancer{} }
func (m *Freelancer) String() string { return proto.CompactTextString(m) }
func (*Freelancer) ProtoMessage()    {}
func (*Freelancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d254e95582394ec6, []int{0}
}

func (m *Freelancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Freelancer.Unmarshal(m, b)
}
func (m *Freelancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Freelancer.Marshal(b, m, deterministic)
}
func (m *Freelancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Freelancer.Merge(m, src)
}
func (m *Freelancer) XXX_Size() int {
	return xxx_messageInfo_Freelancer.Size(m)
}
func (m *Freelancer) XXX_DiscardUnknown() {
	xxx_messageInfo_Freelancer.DiscardUnknown(m)
}

var xxx_messageInfo_Freelancer proto.InternalMessageInfo

func (m *Freelancer) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Freelancer) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Freelancer) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Freelancer) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Freelancer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Freelancer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Freelancer) GetTagLine() string {
	if m != nil {
		return m.TagLine
	}
	return ""
}

func (m *Freelancer) GetOverview() string {
	if m != nil {
		return m.Overview
	}
	return ""
}

func (m *Freelancer) GetExperienceLevelId() int64 {
	if m != nil {
		return m.ExperienceLevelId
	}
	return 0
}

func (m *Freelancer) GetSpecialityId() int64 {
	if m != nil {
		return m.SpecialityId
	}
	return 0
}

type FreelancerID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreelancerID) Reset()         { *m = FreelancerID{} }
func (m *FreelancerID) String() string { return proto.CompactTextString(m) }
func (*FreelancerID) ProtoMessage()    {}
func (*FreelancerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d254e95582394ec6, []int{1}
}

func (m *FreelancerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreelancerID.Unmarshal(m, b)
}
func (m *FreelancerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreelancerID.Marshal(b, m, deterministic)
}
func (m *FreelancerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreelancerID.Merge(m, src)
}
func (m *FreelancerID) XXX_Size() int {
	return xxx_messageInfo_FreelancerID.Size(m)
}
func (m *FreelancerID) XXX_DiscardUnknown() {
	xxx_messageInfo_FreelancerID.DiscardUnknown(m)
}

var xxx_messageInfo_FreelancerID proto.InternalMessageInfo

func (m *FreelancerID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d254e95582394ec6, []int{2}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Freelancer)(nil), "freelancer_grpc.Freelancer")
	proto.RegisterType((*FreelancerID)(nil), "freelancer_grpc.FreelancerID")
	proto.RegisterType((*UserID)(nil), "freelancer_grpc.UserID")
}

func init() {
	proto.RegisterFile("internal/app/freelancer/delivery/grpc/freelancer_grpc/freelancer.proto", fileDescriptor_d254e95582394ec6)
}

var fileDescriptor_d254e95582394ec6 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xfa, 0x3f, 0x14, 0xb5, 0x8b, 0xe0, 0x52, 0x7f, 0x28, 0xb9, 0xea, 0x85, 0x34,
	0xa0, 0x4f, 0xd0, 0x1f, 0x4b, 0x03, 0x05, 0xa5, 0xea, 0xb5, 0xac, 0xd9, 0xb1, 0x2e, 0x84, 0x4d,
	0x98, 0xc6, 0x68, 0xde, 0xc6, 0x97, 0xf3, 0x3d, 0x24, 0x9b, 0xda, 0xc6, 0x54, 0x14, 0xbc, 0xdb,
	0x73, 0xce, 0x37, 0x87, 0x30, 0x19, 0x98, 0x2a, 0x1d, 0x23, 0x69, 0x11, 0xb8, 0x22, 0x8a, 0xdc,
	0x27, 0x42, 0x0c, 0x84, 0xf6, 0x91, 0x5c, 0x89, 0x81, 0x4a, 0x90, 0x52, 0x77, 0x49, 0x91, 0x5f,
	0x08, 0x1e, 0x4a, 0x7a, 0x10, 0x51, 0x18, 0x87, 0x6c, 0xbf, 0x44, 0x38, 0xef, 0x36, 0xc0, 0x74,
	0xe3, 0xb1, 0x3d, 0xb0, 0xbd, 0x09, 0xb7, 0x7a, 0x56, 0xbf, 0xb2, 0xb0, 0xbd, 0x09, 0x3b, 0x81,
	0xd6, 0xd0, 0xf7, 0xc3, 0x17, 0x1d, 0x7b, 0x92, 0xdb, 0xc6, 0xde, 0x1a, 0x8c, 0x43, 0x63, 0x9c,
	0x3d, 0x29, 0xe5, 0x95, 0x9e, 0xd5, 0x6f, 0x2d, 0xbe, 0x24, 0x63, 0x50, 0x1d, 0xab, 0x38, 0xe5,
	0x55, 0x63, 0x9b, 0x77, 0x46, 0x0f, 0xa5, 0x24, 0x5c, 0xad, 0x78, 0x2d, 0xa7, 0xd7, 0x92, 0x1d,
	0x42, 0xed, 0xe6, 0x39, 0xd4, 0xc8, 0xeb, 0xc6, 0xcf, 0x45, 0xc6, 0xdf, 0x89, 0xe5, 0x5c, 0x69,
	0xe4, 0x8d, 0x9c, 0x5f, 0x4b, 0xd6, 0x85, 0xe6, 0x75, 0x82, 0x94, 0x28, 0x7c, 0xe5, 0x4d, 0x13,
	0x6d, 0x34, 0x3b, 0x87, 0xce, 0xd5, 0x5b, 0x84, 0xa4, 0x50, 0xfb, 0x38, 0xc7, 0x04, 0x03, 0x4f,
	0xf2, 0x96, 0xf9, 0xf2, 0xdd, 0x80, 0x39, 0xd0, 0xbe, 0x8d, 0xd0, 0x57, 0x22, 0x50, 0x71, 0xea,
	0x49, 0x0e, 0x06, 0xfc, 0xe6, 0x39, 0x67, 0xd0, 0xde, 0x6e, 0xc8, 0x9b, 0x94, 0x77, 0xe4, 0x70,
	0xa8, 0xdf, 0xaf, 0x7e, 0x4a, 0x2e, 0x3e, 0x2c, 0xe8, 0x6c, 0x47, 0x67, 0x42, 0xcb, 0x00, 0x89,
	0xcd, 0xe0, 0x60, 0x4c, 0x28, 0x62, 0x2c, 0xec, 0xfd, 0x68, 0x50, 0xfa, 0x31, 0x83, 0xbc, 0xb2,
	0x7b, 0xbc, 0x13, 0x14, 0xa6, 0x46, 0x90, 0x1d, 0x86, 0x1c, 0xa5, 0x19, 0xfc, 0xef, 0x8e, 0x6a,
	0xd6, 0xc1, 0x4e, 0x7f, 0x81, 0xfe, 0xe8, 0x78, 0xac, 0x9b, 0xe3, 0xba, 0xfc, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0xb4, 0xd1, 0xbe, 0xe2, 0xa6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FreelancerHandlerClient is the client API for FreelancerHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FreelancerHandlerClient interface {
	CreateFreelancer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Freelancer, error)
	FindByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Freelancer, error)
	Find(ctx context.Context, in *FreelancerID, opts ...grpc.CallOption) (*Freelancer, error)
}

type freelancerHandlerClient struct {
	cc *grpc.ClientConn
}

func NewFreelancerHandlerClient(cc *grpc.ClientConn) FreelancerHandlerClient {
	return &freelancerHandlerClient{cc}
}

func (c *freelancerHandlerClient) CreateFreelancer(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Freelancer, error) {
	out := new(Freelancer)
	err := c.cc.Invoke(ctx, "/freelancer_grpc.FreelancerHandler/CreateFreelancer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerHandlerClient) FindByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Freelancer, error) {
	out := new(Freelancer)
	err := c.cc.Invoke(ctx, "/freelancer_grpc.FreelancerHandler/FindByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerHandlerClient) Find(ctx context.Context, in *FreelancerID, opts ...grpc.CallOption) (*Freelancer, error) {
	out := new(Freelancer)
	err := c.cc.Invoke(ctx, "/freelancer_grpc.FreelancerHandler/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreelancerHandlerServer is the server API for FreelancerHandler service.
type FreelancerHandlerServer interface {
	CreateFreelancer(context.Context, *UserID) (*Freelancer, error)
	FindByUser(context.Context, *UserID) (*Freelancer, error)
	Find(context.Context, *FreelancerID) (*Freelancer, error)
}

// UnimplementedFreelancerHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedFreelancerHandlerServer struct {
}

func (*UnimplementedFreelancerHandlerServer) CreateFreelancer(ctx context.Context, req *UserID) (*Freelancer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFreelancer not implemented")
}
func (*UnimplementedFreelancerHandlerServer) FindByUser(ctx context.Context, req *UserID) (*Freelancer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByUser not implemented")
}
func (*UnimplementedFreelancerHandlerServer) Find(ctx context.Context, req *FreelancerID) (*Freelancer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterFreelancerHandlerServer(s *grpc.Server, srv FreelancerHandlerServer) {
	s.RegisterService(&_FreelancerHandler_serviceDesc, srv)
}

func _FreelancerHandler_CreateFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerHandlerServer).CreateFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/freelancer_grpc.FreelancerHandler/CreateFreelancer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerHandlerServer).CreateFreelancer(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerHandler_FindByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerHandlerServer).FindByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/freelancer_grpc.FreelancerHandler/FindByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerHandlerServer).FindByUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerHandler_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreelancerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerHandlerServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/freelancer_grpc.FreelancerHandler/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerHandlerServer).Find(ctx, req.(*FreelancerID))
	}
	return interceptor(ctx, in, info, handler)
}

var _FreelancerHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "freelancer_grpc.FreelancerHandler",
	HandlerType: (*FreelancerHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFreelancer",
			Handler:    _FreelancerHandler_CreateFreelancer_Handler,
		},
		{
			MethodName: "FindByUser",
			Handler:    _FreelancerHandler_FindByUser_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _FreelancerHandler_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/freelancer/delivery/grpc/freelancer_grpc/freelancer.proto",
}
