// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/job/delivery/grpc/job_grpc/job.proto

package job_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	HireManagerId        int64                `protobuf:"varint,2,opt,name=HireManagerId,proto3" json:"HireManagerId,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Files                string               `protobuf:"bytes,5,opt,name=Files,proto3" json:"Files,omitempty"`
	SpecialityId         int64                `protobuf:"varint,6,opt,name=SpecialityId,proto3" json:"SpecialityId,omitempty"`
	ExperienceLevelId    int64                `protobuf:"varint,7,opt,name=ExperienceLevelId,proto3" json:"ExperienceLevelId,omitempty"`
	PaymentAmount        float32              `protobuf:"fixed32,8,opt,name=PaymentAmount,proto3" json:"PaymentAmount,omitempty"`
	Country              int64                `protobuf:"varint,9,opt,name=Country,proto3" json:"Country,omitempty"`
	City                 int64                `protobuf:"varint,10,opt,name=City,proto3" json:"City,omitempty"`
	JobTypeId            int64                `protobuf:"varint,11,opt,name=JobTypeId,proto3" json:"JobTypeId,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,12,opt,name=Date,proto3" json:"Date,omitempty"`
	Status               string               `protobuf:"bytes,13,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c8b801cdea31cc, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Job) GetHireManagerId() int64 {
	if m != nil {
		return m.HireManagerId
	}
	return 0
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetFiles() string {
	if m != nil {
		return m.Files
	}
	return ""
}

func (m *Job) GetSpecialityId() int64 {
	if m != nil {
		return m.SpecialityId
	}
	return 0
}

func (m *Job) GetExperienceLevelId() int64 {
	if m != nil {
		return m.ExperienceLevelId
	}
	return 0
}

func (m *Job) GetPaymentAmount() float32 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

func (m *Job) GetCountry() int64 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *Job) GetCity() int64 {
	if m != nil {
		return m.City
	}
	return 0
}

func (m *Job) GetJobTypeId() int64 {
	if m != nil {
		return m.JobTypeId
	}
	return 0
}

func (m *Job) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type JobID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobID) Reset()         { *m = JobID{} }
func (m *JobID) String() string { return proto.CompactTextString(m) }
func (*JobID) ProtoMessage()    {}
func (*JobID) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c8b801cdea31cc, []int{1}
}

func (m *JobID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobID.Unmarshal(m, b)
}
func (m *JobID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobID.Marshal(b, m, deterministic)
}
func (m *JobID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobID.Merge(m, src)
}
func (m *JobID) XXX_Size() int {
	return xxx_messageInfo_JobID.Size(m)
}
func (m *JobID) XXX_DiscardUnknown() {
	xxx_messageInfo_JobID.DiscardUnknown(m)
}

var xxx_messageInfo_JobID proto.InternalMessageInfo

func (m *JobID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c8b801cdea31cc, []int{2}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "job_grpc.Job")
	proto.RegisterType((*JobID)(nil), "job_grpc.JobID")
	proto.RegisterType((*UserID)(nil), "job_grpc.UserID")
}

func init() {
	proto.RegisterFile("internal/app/job/delivery/grpc/job_grpc/job.proto", fileDescriptor_37c8b801cdea31cc)
}

var fileDescriptor_37c8b801cdea31cc = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x49, 0x7f, 0xdd, 0x75, 0x7a, 0xf5, 0xc7, 0x20, 0xba, 0x14, 0xc1, 0x50, 0x44, 0xfa,
	0x20, 0x09, 0x9e, 0x0f, 0x3e, 0xcb, 0xc5, 0x7a, 0x29, 0x0a, 0xd2, 0xab, 0xcf, 0xb2, 0x49, 0xc6,
	0xb0, 0xb2, 0xd9, 0x5d, 0x36, 0xdb, 0xc3, 0xfc, 0x21, 0xfe, 0xbf, 0x92, 0x8d, 0xa1, 0xe6, 0xfa,
	0x36, 0xf3, 0xf9, 0x7e, 0x67, 0x96, 0xf9, 0x26, 0xf0, 0x4e, 0x28, 0x47, 0x56, 0x71, 0x19, 0x73,
	0x63, 0xe2, 0x5f, 0x3a, 0x8b, 0x0b, 0x92, 0xe2, 0x9e, 0x6c, 0x13, 0x97, 0xd6, 0xe4, 0x2d, 0xf9,
	0xd1, 0x17, 0x91, 0xb1, 0xda, 0x69, 0xbc, 0xec, 0xd9, 0xea, 0x55, 0xa9, 0x75, 0x29, 0x29, 0xf6,
	0x3c, 0x3b, 0xfe, 0x8c, 0x9d, 0xa8, 0xa8, 0x76, 0xbc, 0x32, 0x9d, 0x75, 0xfd, 0x67, 0x0c, 0xe3,
	0x9d, 0xce, 0xf0, 0x11, 0x8c, 0xd2, 0x84, 0x05, 0x61, 0xb0, 0x19, 0xef, 0x47, 0x69, 0x82, 0xaf,
	0x61, 0x79, 0x2b, 0x2c, 0x7d, 0xe5, 0x8a, 0x97, 0x64, 0xd3, 0x82, 0x8d, 0xbc, 0x34, 0x84, 0xf8,
	0x0c, 0xa6, 0x07, 0xe1, 0x24, 0xb1, 0x71, 0x18, 0x6c, 0xe6, 0xfb, 0xae, 0xc1, 0x10, 0x16, 0x09,
	0xd5, 0xb9, 0x15, 0xc6, 0x09, 0xad, 0xd8, 0xc4, 0x6b, 0xff, 0xa3, 0x76, 0x6e, 0x2b, 0x24, 0xd5,
	0x6c, 0xda, 0xcd, 0xf9, 0x06, 0xd7, 0x70, 0x75, 0x67, 0x28, 0x17, 0x5c, 0x0a, 0xd7, 0xa4, 0x05,
	0x9b, 0xf9, 0x27, 0x07, 0x0c, 0xdf, 0xc2, 0xd3, 0x4f, 0xbf, 0x0d, 0x59, 0x41, 0x2a, 0xa7, 0x2f,
	0x74, 0x4f, 0x32, 0x2d, 0xd8, 0x85, 0x37, 0x9e, 0x0b, 0xed, 0x15, 0xdf, 0x78, 0x53, 0x91, 0x72,
	0x1f, 0x2b, 0x7d, 0x54, 0x8e, 0x5d, 0x86, 0xc1, 0x66, 0xb4, 0x1f, 0x42, 0x64, 0x70, 0x71, 0xd3,
	0x16, 0xb6, 0x61, 0x73, 0xbf, 0xa9, 0x6f, 0x11, 0x61, 0x72, 0x23, 0x5c, 0xc3, 0xc0, 0x63, 0x5f,
	0xe3, 0x4b, 0x98, 0xef, 0x74, 0x76, 0x68, 0x0c, 0xa5, 0x05, 0x5b, 0x78, 0xe1, 0x04, 0x30, 0x82,
	0x49, 0xc2, 0x1d, 0xb1, 0xab, 0x30, 0xd8, 0x2c, 0xae, 0x57, 0x51, 0x97, 0x7f, 0xd4, 0xe7, 0x1f,
	0x1d, 0xfa, 0xfc, 0xf7, 0xde, 0x87, 0xcf, 0x61, 0x76, 0xe7, 0xb8, 0x3b, 0xd6, 0x6c, 0xe9, 0xa3,
	0xf8, 0xd7, 0xad, 0x5f, 0xc0, 0x74, 0xa7, 0xb3, 0x34, 0x79, 0xf8, 0x61, 0xd6, 0x0c, 0x66, 0xdf,
	0x6b, 0xb2, 0xe7, 0xca, 0x75, 0x05, 0xb0, 0xd3, 0xd9, 0x2d, 0x57, 0x85, 0x24, 0x8b, 0x6f, 0x60,
	0xb2, 0x15, 0xaa, 0xc0, 0xc7, 0x51, 0xff, 0x33, 0x44, 0x7e, 0xe1, 0x6a, 0x39, 0x00, 0xf8, 0x01,
	0xf0, 0x33, 0xb9, 0x6e, 0xe5, 0xd6, 0xea, 0xaa, 0x7b, 0xf5, 0x6c, 0xea, 0xc9, 0x09, 0x74, 0xde,
	0x6c, 0xe6, 0x6f, 0x7a, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x5a, 0x02, 0xeb, 0xa0, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobHandlerClient is the client API for JobHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobHandlerClient interface {
	Find(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*Job, error)
	GetUserIDFromJobID(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*UserID, error)
}

type jobHandlerClient struct {
	cc *grpc.ClientConn
}

func NewJobHandlerClient(cc *grpc.ClientConn) JobHandlerClient {
	return &jobHandlerClient{cc}
}

func (c *jobHandlerClient) Find(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/job_grpc.JobHandler/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobHandlerClient) GetUserIDFromJobID(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*UserID, error) {
	out := new(UserID)
	err := c.cc.Invoke(ctx, "/job_grpc.JobHandler/GetUserIDFromJobID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobHandlerServer is the server API for JobHandler service.
type JobHandlerServer interface {
	Find(context.Context, *JobID) (*Job, error)
	GetUserIDFromJobID(context.Context, *JobID) (*UserID, error)
}

// UnimplementedJobHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedJobHandlerServer struct {
}

func (*UnimplementedJobHandlerServer) Find(ctx context.Context, req *JobID) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedJobHandlerServer) GetUserIDFromJobID(ctx context.Context, req *JobID) (*UserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIDFromJobID not implemented")
}

func RegisterJobHandlerServer(s *grpc.Server, srv JobHandlerServer) {
	s.RegisterService(&_JobHandler_serviceDesc, srv)
}

func _JobHandler_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHandlerServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_grpc.JobHandler/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHandlerServer).Find(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobHandler_GetUserIDFromJobID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHandlerServer).GetUserIDFromJobID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_grpc.JobHandler/GetUserIDFromJobID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHandlerServer).GetUserIDFromJobID(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job_grpc.JobHandler",
	HandlerType: (*JobHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _JobHandler_Find_Handler,
		},
		{
			MethodName: "GetUserIDFromJobID",
			Handler:    _JobHandler_GetUserIDFromJobID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/job/delivery/grpc/job_grpc/job.proto",
}
