// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/manager/delivery/grpc/manager_grpc/manager_grpc.proto

package manager_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Manager struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AccountId            int64                `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RegistrationDate     *timestamp.Timestamp `protobuf:"bytes,3,opt,name=RegistrationDate,proto3" json:"RegistrationDate,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	CompanyId            int64                `protobuf:"varint,5,opt,name=CompanyId,proto3" json:"CompanyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Manager) Reset()         { *m = Manager{} }
func (m *Manager) String() string { return proto.CompactTextString(m) }
func (*Manager) ProtoMessage()    {}
func (*Manager) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f51de7806f00cac, []int{0}
}

func (m *Manager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manager.Unmarshal(m, b)
}
func (m *Manager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manager.Marshal(b, m, deterministic)
}
func (m *Manager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager.Merge(m, src)
}
func (m *Manager) XXX_Size() int {
	return xxx_messageInfo_Manager.Size(m)
}
func (m *Manager) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager.DiscardUnknown(m)
}

var xxx_messageInfo_Manager proto.InternalMessageInfo

func (m *Manager) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Manager) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Manager) GetRegistrationDate() *timestamp.Timestamp {
	if m != nil {
		return m.RegistrationDate
	}
	return nil
}

func (m *Manager) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Manager) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

type UserID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f51de7806f00cac, []int{1}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Info struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CompanyID            int64    `protobuf:"varint,2,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f51de7806f00cac, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Info) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Manager)(nil), "manager_grpc.Manager")
	proto.RegisterType((*UserID)(nil), "manager_grpc.UserID")
	proto.RegisterType((*Info)(nil), "manager_grpc.Info")
}

func init() {
	proto.RegisterFile("internal/app/manager/delivery/grpc/manager_grpc/manager_grpc.proto", fileDescriptor_2f51de7806f00cac)
}

var fileDescriptor_2f51de7806f00cac = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xe9, 0x36, 0xa7, 0xbb, 0xea, 0x90, 0xa0, 0x12, 0x8a, 0xe0, 0xd8, 0xd3, 0x9e, 0x1a,
	0x98, 0x4f, 0x8a, 0x2f, 0x6e, 0x65, 0x18, 0xd0, 0x97, 0xa2, 0xcf, 0x92, 0xb5, 0x77, 0x25, 0xd0,
	0x26, 0x21, 0xcb, 0x84, 0xfd, 0x02, 0x7f, 0x93, 0xff, 0x4e, 0xd6, 0x2e, 0x73, 0x75, 0xf8, 0x78,
	0xbf, 0x7b, 0x6e, 0xce, 0xc9, 0x81, 0x89, 0x54, 0x0e, 0xad, 0x12, 0x05, 0x13, 0xc6, 0xb0, 0x52,
	0x28, 0x91, 0xa3, 0x65, 0x19, 0x16, 0xf2, 0x13, 0xed, 0x9a, 0xe5, 0xd6, 0xa4, 0x9e, 0x7e, 0x1c,
	0x0c, 0x91, 0xb1, 0xda, 0x69, 0x72, 0xb6, 0xcf, 0xc2, 0xdb, 0x5c, 0xeb, 0xbc, 0x40, 0x56, 0xed,
	0xe6, 0xab, 0x05, 0x73, 0xb2, 0xc4, 0xa5, 0x13, 0xa5, 0xa9, 0xe5, 0xc3, 0xef, 0x00, 0x8e, 0x5f,
	0xeb, 0x0b, 0xd2, 0x87, 0x16, 0x8f, 0x69, 0x30, 0x08, 0x46, 0xed, 0xa4, 0xc5, 0x63, 0x72, 0x03,
	0xbd, 0xa7, 0x34, 0xd5, 0x2b, 0xe5, 0x78, 0x46, 0x5b, 0x15, 0xfe, 0x05, 0x64, 0x06, 0x17, 0x09,
	0xe6, 0x72, 0xe9, 0xac, 0x70, 0x52, 0xab, 0x58, 0x38, 0xa4, 0xed, 0x41, 0x30, 0x3a, 0x1d, 0x87,
	0x51, 0xed, 0x1a, 0x79, 0xd7, 0xe8, 0xcd, 0xbb, 0x26, 0x07, 0x37, 0x24, 0x84, 0x93, 0x17, 0x9d,
	0x56, 0x33, 0xed, 0x0c, 0x82, 0x51, 0x2f, 0xd9, 0xcd, 0x9b, 0x04, 0x53, 0x5d, 0x1a, 0xa1, 0xd6,
	0x3c, 0xa3, 0x47, 0x75, 0x82, 0x1d, 0x18, 0x52, 0xe8, 0xbe, 0x2f, 0xd1, 0xf2, 0xf8, 0x6f, 0xf2,
	0xe1, 0x23, 0x74, 0xb8, 0x5a, 0x68, 0x72, 0xed, 0x15, 0xdb, 0x9d, 0xd7, 0xef, 0xbd, 0x1b, 0xfb,
	0x9f, 0xed, 0xc0, 0xf8, 0x2b, 0x80, 0xfe, 0xb6, 0x93, 0x67, 0xa1, 0xb2, 0x02, 0x2d, 0x79, 0x80,
	0xf3, 0xa9, 0x45, 0xe1, 0xd0, 0x77, 0x45, 0xa2, 0x46, 0xf7, 0x1b, 0xb7, 0xf0, 0xaa, 0xc9, 0xbc,
	0xf4, 0x1e, 0x60, 0x26, 0x55, 0x36, 0x59, 0x6f, 0xcc, 0xc9, 0x65, 0x53, 0x54, 0x07, 0xfa, 0xe7,
	0x74, 0xde, 0xad, 0x1a, 0xbc, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xa8, 0xee, 0x53, 0x19,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerHandlerClient is the client API for ManagerHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerHandlerClient interface {
	CreateManager(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Manager, error)
	FindByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Manager, error)
}

type managerHandlerClient struct {
	cc *grpc.ClientConn
}

func NewManagerHandlerClient(cc *grpc.ClientConn) ManagerHandlerClient {
	return &managerHandlerClient{cc}
}

func (c *managerHandlerClient) CreateManager(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Manager, error) {
	out := new(Manager)
	err := c.cc.Invoke(ctx, "/manager_grpc.ManagerHandler/CreateManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerHandlerClient) FindByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Manager, error) {
	out := new(Manager)
	err := c.cc.Invoke(ctx, "/manager_grpc.ManagerHandler/FindByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerHandlerServer is the server API for ManagerHandler service.
type ManagerHandlerServer interface {
	CreateManager(context.Context, *Info) (*Manager, error)
	FindByUser(context.Context, *UserID) (*Manager, error)
}

// UnimplementedManagerHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedManagerHandlerServer struct {
}

func (*UnimplementedManagerHandlerServer) CreateManager(ctx context.Context, req *Info) (*Manager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManager not implemented")
}
func (*UnimplementedManagerHandlerServer) FindByUser(ctx context.Context, req *UserID) (*Manager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByUser not implemented")
}

func RegisterManagerHandlerServer(s *grpc.Server, srv ManagerHandlerServer) {
	s.RegisterService(&_ManagerHandler_serviceDesc, srv)
}

func _ManagerHandler_CreateManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerHandlerServer).CreateManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_grpc.ManagerHandler/CreateManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerHandlerServer).CreateManager(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerHandler_FindByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerHandlerServer).FindByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_grpc.ManagerHandler/FindByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerHandlerServer).FindByUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manager_grpc.ManagerHandler",
	HandlerType: (*ManagerHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateManager",
			Handler:    _ManagerHandler_CreateManager_Handler,
		},
		{
			MethodName: "FindByUser",
			Handler:    _ManagerHandler_FindByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/manager/delivery/grpc/manager_grpc/manager_grpc.proto",
}
